DROP TABLE IF EXISTS attendees CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS fields CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS rankings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS profile CASCADE;
DROP TABLE IF EXISTS requests CASCADE;

